import Head from "next/head";
import Image from "next/image";
import {
  Container,
  Grid,
  Toolbar,
  Skeleton,
  Box,
  Divider,
} from "@mui/material";
import { Fragment, useState } from "react";

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container maxWidth='lg'>
        <Toolbar id='back-to-top-anchor' />
        <main>
          <Grid container spacing={4}></Grid>
          <h1>Hello</h1>
        </main>
      </Container>
    </>
  );
}
